### ISSUE TITLE
ENH: sh_full report

### ISSUE THREAD

**Issue by westurner** [westurner/pyrpo#8]
Create an .sh with commented output lines for `# status` and `# log`

**Objectives**
- `diff`-able `pyrpo.rebuild-full.sh` reports 

**Output**:

```
### [pyrpo commandline]
## hostname
## datetime

## <path> 
git clone <url> <path>
git remote add/remove/update <./path> <url>
# status
# logs
## </path>
```

**Current Support**
- `pyrpo -r sh`
- `pyrpo -r status`
- `pyrpo -r full`

**Questions**
- Would it make sense to store this in a repository?
  
  Sort of. `status` and `output` likely differ from environment to environment

**TODO**
- [ ] Pick and implement {`GitRev`, `HgRev`, ...} `__str__` syntax
- [ ] Add an `sh_full` report + option
- [ ] Add a default option and/or output filepath for these types of reports
  
  (`--sh-full`, `--sh-rebuild`, `--awesome`)
- [ ] Prefix status lines with `#`
- [ ] Prefix log lines (split by `\n`) with `#`
- [ ] Add a commented commandline args + hostname header
